### ISSUE TITLE
New Visualization: Bus Factor 

### ISSUE THREAD

**Issue by cdolfi** [oss-aspen/8Knot#114]
**Please describe the background and context for this new visualization**
The Bus Factor is a compelling metric because it visualizes the question "how many contributors can we lose before a project stalls?" by hypothetically having these people get run over by a bus (more pleasantly, how many would have to win in a lottery and decide to move on).

The Bus Factor is the smallest number of people that make 50% of contributions.
**Describe the perspective you'd like the final visual to give**
https://chaoss.community/metric-bus-factor/

**Describe the acceptance criteria for the issue and visualization to be complete**
when the issue is taken on, the people working on this should edit to describe the steps necessary to complete this as a visualization in the explorer dashboard

**Comment by christinaexyou** [comment]
@JamesKunstle please assign me to this issue.

**Comment by JamesKunstle** [comment]
Some other interesting parameters:

If the definition of bus factor is "smallest number of people that make YY% of contributions." let the user set YY as a parameter.

Calculate bus factor over time using a time window of a parameterized width and step, e.g. "in six month windows, sliding by four months as a time, from <date> to <later date>."

Allow the user to screen out names by some regular expression from the bus factor, e.g. '-bot' names.

Allow the user to screen out outlier contributors (bots that aren't labelled 'bot' perhaps) all at once, but list the contributors who are green-lit (extremely active contributors who are outliers and not bots).

**Comment by JamesKunstle** [comment]
Christina's initial analysis is merged into Rappel. Cali and Christina are working on Bus Factor integration into 8K.

**Comment by JamesKunstle** [comment]
UPDATE: PR for notebook is done, now using this issue to track integration of analysis into application.

**Comment by cdolfi** [comment]
closed with line and pie chart visualizations merged
