### ISSUE TITLE
Number of PRs/ Issues with no assignments per repo/ collection of repos

### ISSUE THREAD

**Issue by schwesig** [oss-aspen/8Knot#162]
**Please describe the background and context for this new visualization**
This visualization could be for the dashboard of a project or team, to see how many issues or PRs are currently without an assignment. Displayed on a timeline, this can be a good indicator, if and how fast issues/ PRs are assigned. The increase/ decrease of unassigned issues/ PRs can show, if the income of issues is growing, or the complexity is getting bigger, or the resources to solve are not enough. 

**Describe the perspective you'd like the final visual to give**
The visualization could be a simple line graph (total numbers), or a stacked bar line or chart (assigned and unassigned) over time.
The filter/ selection should be possible for 1 or multiple repos, in case a project or team works on more than one repo.
Furthermore the selection of only issues, only PRs or both would be a benefit.

**Acceptance criteria for the issue and visualization to be complete**
- [ ] Augur Query
- [ ] Preprocess data into pandas data frame format for visualization
- [ ] Plotly graph creation
- [ ] Notes with any background context that would be useful for Explorer integration
- [ ] Open issue on explorer for visualization integration using template

**Additional context**
If the age of an issue (creation of issue/ PR to date in the chart) could be shown (by color or place in the chart), that could make it easier to figure out the reasons (for a growing of unassigned issues).
Clusters to be less confusing could be made (e.g. Age x<=1 day, 1 day<x<=2 days, 2 days<x<=5 days, 5 days<x<=14 days, x>14 days)

for example
![Unassigned Issues, Unassignes PRs, Assigned Issues and Assigned PRs (1)](https://user-images.githubusercontent.com/89909507/192323418-6bda33fc-c539-4636-b142-8ed06ed4dbc1.png)

for example Additional Context
![Una  I  1d, Una  I  2d, Una  I  5d, Una  I  14d, Una  I  _14d…](https://user-images.githubusercontent.com/89909507/192293519-19e7768b-7efb-49e3-ad8b-68de28948f32.png)

**Comment by schwesig** [comment]
Hi /cc @cdolfi
here my input from our call.
Separated into two issues.
This is the first (higher priority).

**Comment by cdolfi** [comment]
Starting to think through this visualization a bit. We do not have the information of when someone is assigned an issue. We only have the current status of assignments. I am trying to think of different edits on this visualization with the limitation
