### ISSUE TITLE
Number of Issues assigned to user, per user, per repo/ collection of repos

### ISSUE THREAD

**Issue by schwesig** [oss-aspen/8Knot#163]
**Please describe the background and context for this new visualization**
This visualization could be for the dashboard of a project or team, to see how much workload there is on a team in general and per user. Displayed on a timeline per team (selection of users) or on a timeline per user. This can be a good indicator, if the complexity or pure amount of issues is getting bigger, or the resources to solve issue/ PRs are not enough for the workload.

**Describe the perspective you'd like the final visual to give**
The visualization could be a simple line graph (total numbers), or a stacked bar line or chart (per user) over time.
The filter/ selection should be possible for 1 or multiple repos & for 1 to many users, in case a user or a team works on more than one repo.
Furthermore the selection of only issues, only PRs or both would be a benefit.

**Acceptance criteria for the issue and visualization to be complete**
- [ ] Augur Query
- [ ] Preprocess data into pandas data frame format for visualization
- [ ] Plotly graph creation
- [ ] Notes with any background context that would be useful for Explorer integration
- [ ] Open issue on explorer for visualization integration using template

**Additional context**
The users should be anonymized or clustered for privacy reasons. If a personal fork of this dashboard wants to put real names into it, that should be on their personal site.
If the age of an issue (creation of issue/ PR to date in the chart) could be shown (by color or place in the chart), that could make it easier to figure out the reasons (for a growing of unassigned issues).
Clusters to be less confusing could be made (e.g. Age x<=1 day, 1 day<x<=2 days, 2 days<x<=5 days, 5 days<x<=14 days, x>14 days)

![USER 1 Open, USER 2 Open, USER 3 Open, USER 4 Open and USER 5 Open (1)](https://user-images.githubusercontent.com/89909507/192323186-51b61234-2c2b-4e2e-90b6-8cef7327e88c.png)

**Comment by schwesig** [comment]
Hi /cc @cdolfi
here my input from our call.
Separated into two issues.
This is the second (lower priority as discussed).

**Comment by cdolfi** [comment]
@schwesig First, this is awesome! This issue will definitely be something I refer people to in the future for examples of visualization requests. Quick question, when you are referring to "workload" what exactly is included in that?

**Comment by schwesig** [comment]
@cdolfi you are referring to this?
> This can be a good indicator, if the complexity or pure amount of issues is getting bigger, or the resources to solve issue/ PRs are not enough for the workload.

from a team/ people view:
when the amount of issues/ PRs are growing over time, there is maybe a higher workload on the service/ more users -> more support, or there are problems that leads to more issues.
if these issues lead to a growing number of not-solved issues over time (TTR goes up), this can mean e.g. issues are getting more complicated and/ or the number of people available to solve these issues are not enough (too much workload for too few people)

did this answer your question?
