### ISSUE TITLE
optimize pandas queries for visualizations

### ISSUE THREAD

**Issue by JamesKunstle** [oss-aspen/8Knot#175]
Augur queries are bloated, requesting lots of unused data and storing strings for integer values naively. Clean these up.

**Comment by JamesKunstle** [comment]
part of the Redis-stabilization milestone

**Comment by JamesKunstle** [comment]
- [ ] switch from CSV to Feather format - look into how to shard large repos
- [ ] more data preprocessing pre-storage.

**Comment by cdolfi** [comment]
@JamesKunstle can this be closed?

**Comment by JamesKunstle** [comment]
@cdolfi no still working on this.

**Comment by JamesKunstle** [comment]
checked total data size. optimizations at this point aren't necessary- app runs fine w/o further optimization, we can focus on optimizations when we're further along.

possible opts include:
- dropping unused data from queries that no callback is using
- cast large integers down and repeated strings to categories
- finally finish csv->feather format if necessary.
