### ISSUE TITLE
Data Request for GitHub repos

### ISSUE THREAD

**Issue by oindrillac** [oss-aspen/8Knot#269]
Hi,

We would like the following GitHub repos to be included into the Augur database

https://github.com/sigstore/cosign
https://github.com/sigstore/gitsign
https://github.com/sigstore/rekor
https://github.com/sigstore/fulcio
https://github.com/sigstore/sigstore
https://github.com/sigstore/sigstore-python
https://github.com/sigstore/sigstore-js
https://github.com/docker/compose
https://github.com/docker/docs
https://github.com/redhat-et/transmission
https://github.com/buildpacks/pack
https://github.com/cilium/cilium
https://github.com/confidential-containers
https://github.com/dapr/dapr
https://github.com/devfile/api
https://github.com/distribution/distribution
https://github.com/redhat-iot/iot-dev
https://github.com/falcosecurity/falco
https://github.com/ebay/go-ovn
https://github.com/grpc/grpc-go
https://github.com/in-toto/in-toto
https://github.com/redhat-et/ipfs-operator
https://github.com/k8gb-io/k8gb
https://github.com/karmada-io/karmada
https://github.com/kiali/kiali
https://github.com/kubeovn/kube-ovn
https://github.com/kubeedge/kubeedge
https://github.com/kudobuilder/kudo
https://github.com/kyverno/kyverno
https://github.com/linkerd/linkerd2
https://github.com/linuxkit/linuxkit
https://github.com/litmuschaos/litmus
https://github.com/meshery/meshery
https://github.com/nats-io/nats-server
https://github.com/noobaa/noobaa-core
https://github.com/gatekeeper/gatekeeper-operator
https://github.com/opencost/opencost
https://github.com/openkruise/kruise
https://github.com/OpenSCAP/openscap
https://github.com/oras-project/oras
https://github.com/ovn-org/ovn-kubernetes
https://github.com/service-mesh-performance/service-mesh-performance
https://github.com/sigstore/rekor
https://github.com/k8snetworkplumbingwg/network-resources-injector
https://github.com/tikv/tikv
https://github.com/tinkerbell/tink
https://github.com/theupdateframework/python-tuf
https://github.com/intel/userspace-cni-network-plugin
https://github.com/volcano-sh/volcano
https://github.com/backube/volsync
https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools
https://github.com/WasmEdge/WasmEdge
https://github.com/kubewarden/policy-server
https://github.com/kubewarden/kubewarden-controller
https://github.com/kubewarden/kwctl
https://github.com/kubewarden/helm-charts
https://github.com/kubewarden/policy-evaluator
https://github.com/networkservicemesh/sdk
https://github.com/networkservicemesh/deployments-k8s
https://github.com/opendatahub-io/odh-manifests
https://github.com/opendatahub-io/opendatahub-operator
https://github.com/opendatahub-io/odh-dashboard
https://github.com/opendatahub-io/opendatahub-community
https://github.com/thoth-station/micropipenv
https://github.com/thoth-station/adviser
https://github.com/thoth-station/core
https://github.com/thoth-station/kebechet
https://github.com/thoth-station/invectio
https://github.com/stackrox/kube-linter
https://github.com/stackrox/stackrox
https://github.com/stackrox/Kubernetes_Security_Specialist_Study_Guide
https://github.com/stackrox/admission-controller-webhook-demo
https://github.com/stackrox/go-grpc-http1
https://github.com/stackrox/helm-charts
https://github.com/falcosecurity/libs
https://github.com/stackrox/kube-linter
https://github.com/cert-manager/cert-manager
https://github.com/istio/istio
https://github.com/istio/community
https://github.com/istio/proxy
https://github.com/istio/istio.io
https://github.com/istio/api
https://github.com/istio/tools
https://github.com/istio/client-go
https://github.com/envoyproxy/envoy
https://github.com/kiali/kiali
https://github.com/serverlessworkflow/specification
https://github.com/serverlessworkflow/synapse
https://github.com/serverlessworkflow/sdk-go
https://github.com/serverlessworkflow/sdk-java
https://github.com/serverlessworkflow/sdk-net
https://github.com/serverlessworkflow/sdk-typescript
https://github.com/shipwright-io/build
https://github.com/tektoncd/pipeline
https://github.com/tektoncd/dashboard
https://github.com/tektoncd/catalog
https://github.com/tektoncd/triggers
https://github.com/tektoncd/cli
https://github.com/tektoncd/operator
https://github.com/tektoncd/community
https://github.com/project-koku/koku
https://github.com/project-koku/koku-ui
https://github.com/project-koku/koku-metrics-operator
https://github.com/argoproj/argo-cd
https://github.com/argoproj/argo-rollouts
https://github.com/kata-containers/kata-containers
https://github.com/kata-containers/community
https://github.com/kata-containers/tests
https://github.com/kubernetes-sigs/cluster-api
https://github.com/quarkusio/quarkus
https://github.com/quarkusio/quarkus-quickstarts
https://github.com/quarkusio/quarkus-workshops
https://github.com/quarkusio/quarkusio.github.io
https://github.com/quarkusio/quarkus-super-heroes
https://github.com/jakartaee/rest
https://github.com/jakartaee/mail-api
https://github.com/jakartaee/servlet
https://github.com/jakartaee/cdi
https://github.com/jakartaee/persistence
https://github.com/apache/camel/
https://github.com/kubernetes/community/
https://github.com/openstack/kuryr
https://github.com/prometheus/prometheus
https://github.com/prometheus/node_exporter
https://github.com/prometheus/alertmanager
https://github.com/prometheus/client_golang
https://github.com/prometheus/blackbox_exporter
https://github.com/prometheus/client_python
https://github.com/prometheus/jmx_exporter
https://github.com/prometheus/pushgateway
https://github.com/prometheus/client_java
https://github.com/prometheus/mysqld_exporter
https://github.com/thanos-io/thanos
https://github.com/vectordotdev/vector
https://github.com/vectordotdev/helm-charts
https://github.com/grafana/loki
https://github.com/open-telemetry/opentelemetry-go
https://github.com/open-telemetry/opentelemetry-specification
https://github.com/open-telemetry/opentelemetry-collector
https://github.com/open-telemetry/opentelemetry-dotnet
https://github.com/open-telemetry/opentelemetry-js
https://github.com/open-telemetry/opentelemetry-collector-contrib
https://github.com/open-telemetry/opentelemetry-java
https://github.com/elastic/elasticsearch
https://github.com/grafana/tempo
https://github.com/etcd-io/etcd
https://github.com/opencontainers/runc
https://github.com/containerd/cgroups
https://github.com/kubevirt/kubevirt
https://github.com/kubevirt/containerized-data-importer
https://github.com/kubevirt/demo
https://github.com/kubevirt/hyperconverged-cluster-operator
https://github.com/kubevirt/kubevirt-ansible
https://github.com/operator-framework
https://github.com/helm/helm
https://github.com/helm/chartmuseum
https://github.com/helm/chart-testing
https://github.com/helm/chart-releaser

cc: @hemajv @cdolfi @sgoggins

**Comment by oindrillac** [comment]
Just an additional fyi - Since these are a lot of projects to add, this list is ordered by priority (projects we would to get included first on top)

**Comment by cdolfi** [comment]
@oindrillac let me check into this, I am pretty sure this is all collected on. There is also now a dashboard to see collection status🎉 so this will be a good time for me to learn how to use it and share with yall

**Comment by sgoggins** [comment]
@oindrillac : These are added in repo_group 222 in the repo_groups table. **Expect to have data at the end of the week.** The repo_group_name is "Issue oss-aspen issue 269". This is useful if you are building queries to SQL directly. 

Note that these repositories are unique insofar as the repositories in this group, unlike most (but not all) others are identified with the github org.

**Comment by sgoggins** [comment]
@oindrillac / @cdolfi : As it turns out there were a couple duplicate repos in the list provided, and 2 of the repos in your csv are actually orgs. https://github.com/confidential-containers and https://github.com/operator-framework .. So, those orgs will not be 222. They will get added though.
