### ISSUE TITLE
NULL values for contributor IDs in Issue table in Augur

### ISSUE THREAD

**Issue by oindrillac** [oss-aspen/8Knot#270]
A majority of values in the `cntrb_id` column for the Issues table are NULL. We need contributor IDs for graph analysis of users and their contribution types. Is it possible to refresh the data for this table?

<img width="575" alt="Screenshot 2023-02-20 at 10 09 39 AM" src="https://user-images.githubusercontent.com/32435206/220143007-4dccdb0e-7ae4-4fb7-9e70-1c4abf8081bf.png">

cc: @hemajv

**Comment by hemajv** [comment]
The `cntrb_id` is also missing for these tables:

- `pull_request_meta`
- `contributors_aliases`
- `pull_request_reviewers`

**Comment by oindrillac** [comment]
And it seems for a lot of rows they are not in the regular integer format and have this UUID format

<img width="571" alt="Screenshot 2023-02-22 at 12 55 16 PM" src="https://user-images.githubusercontent.com/32435206/220714510-d5666091-44f5-46c4-bcd0-85456cab459d.png">

**Comment by sgoggins** [comment]
Which database is being used in this case?

**Comment by sgoggins** [comment]
We could resolve it by calling the event API when retrieving issue data, however we're already collecting all the events and are trying to take a minimalist approach to API calls if we can derive the data in ways like this.

**Comment by sgoggins** [comment]
We could create a materialized view for now also, so all the data is in one place.

**Comment by cdolfi** [comment]
@hemajv @oindrillac

**Comment by oindrillac** [comment]
thanks for looking into this @sgoggins. Will look into the reporter_id for issues. Do you know the reason for the missing (<NA>) `cntrb_id` in the pull_request_meta, contributors_aliases, pull_request_reviewers tables?

The database I am looking into is `padres` I believe this is where the latest data is being loaded into? earlier I was looking into `sandiego` which also had some missing vals.

I noticed that in the `pull_request_meta` table, the `cntrb_id` holds some strange contributor ID type, seems like they are all UUID types like 01017c8d-2a00-0000-0000-000000000000, which is different from other tables. Do you know whats going on here?

The query that I am using is :
```
  SET SCHEMA 'augur_data';
  SELECT r.repo_id,
  r.repo_git,
  r.repo_name,
  prr.cntrb_id,
  prr.pull_request_id
  FROM
  repo r, pull_request_reviewers prr
  WHERE
  prr.repo_id = \'{repo_id}\' AND
  prr.repo_id = r.repo_id
```

**Comment by oindrillac** [comment]
I was able to get contributor IDs from the issue_events table like you suggested @sgoggins and the contributor IDs that I am getting are UUID type. Is that the new datatype for contributor IDs in the database ? 

The earlier format we saw was integers. (we were looking at the sandiego database)
```
  SET SCHEMA 'augur_data';
  SELECT r.repo_id,
  r.repo_git,
  r.repo_name,
  ie.cntrb_id,
  ie.action,
  i.issue_id,
  i.created_at
  FROM
  repo r, issues i, issue_events ie
   WHERE
  i.repo_id = \'{repo_id}\' AND
  i.repo_id = r.repo_id AND
  i.issue_id = ie.issue_id AND
  ie.action='closed'
```
<img width="1098" alt="Screenshot 2023-02-27 at 5 32 38 PM" src="https://user-images.githubusercontent.com/32435206/221701330-41b8a287-7f50-42ab-a9e4-6a38348fa385.png">

**Comment by sgoggins** [comment]
@oindrillac : Yes, UUIDs are now used instead of integers. Our encoding strategy will generate identical UUIDs for the same person across Augur instances.
