### ISSUE TITLE
if an augur group from front end is empty, show error and don't update

### ISSUE THREAD

**Issue by JamesKunstle** [oss-aspen/8Knot#275]

**Comment by sgoggins** [comment]
@JamesKunstle : I think we need a design session around this one.

**Comment by JamesKunstle** [comment]
@sgoggins Yeah agreed. Something that would be interesting is how to tell users that the group is empty (1) because they haven't added anything vs. (2) because some items in the group are waiting to be collected.

**Comment by JamesKunstle** [comment]
This is _sorta_ being handled by #311 because we ignore any groups of size 0. I think that this solves this issue but another issue could be raised detailing how the user might be notified that their group has no repos in it.

**Comment by cdolfi** [comment]
@JamesKunstle My initial thoughts on this is to close this issue/move to backlog wait and see what the user experience/feedback is to come up with a solution or to see if its necessary to have more than just the groups with no repos not populating in the search bar

**Comment by JamesKunstle** [comment]
@cdolfi that's fair. let's close this issue and see if it's a problem.
