### ISSUE TITLE
SCaLE Workshop TODOS

### ISSUE THREAD

**Issue by cdolfi** [oss-aspen/8Knot#279]
cali 
- [x] create slidedeck for overall workshop 
- [x] Make new visualization #284 
- [x] edit OSSNA presentation for part 3 of the workshop 
- [x] create materials for pt 4 
- [x] Create finalized google doc with itinerary, all links, and area to copy and paste things for participants 
- [x] determine the 8knot/Aspen introduction materials for beginning (James duo) 
- [x] go through complete mental walk through of the resources for workshop and determine any holes

https://docs.google.com/document/d/1IA3zPM6Nf5GizE9hwm7Vz2_NQBpbt6Pkqzs3nDDLxM8/edit

James
- [x] Confirm EC2 hardware requirement for SCaLE 8K and Augur, price/instance/hour.
- [x] Configure EC2 instance for 8K, Augur: Networking, Package updates, Docker, Docker compose.
- [x] Test deployment + collection on Augur; learn app lifecycle and collection trigger.
- [x] Validate concurrent Aug+8K deployment on bare metal (Redis collision?).
- [x] Update 8K docs, README, License, and Login (not for SCaLE but for good measure)
- [x] Author Augur deployment + collection and 8K deployment + augur connection slides.
- [x] Author 8K architecture overview slides (part 4 of workshop).
- [x] Validate workshop technical requirements with third party.

**Comment by cdolfi** [comment]
whiteboard/google doc to share links

**Comment by JamesKunstle** [comment]
_Confirm EC2 hardware requirement for SCaLE 8K and Augur, _price/instance/hour.__

Checked that t3.xlarge works for 8Knot. 5gigabit, 4vCPU, 16GB memory seems sufficient for app.
Just set the security group to open TCP for port 8050 and didn't have to mess with NGINX on this first pass.

**Comment by JamesKunstle** [comment]
_ Configure EC2 instance for 8K, Augur: Networking, Package updates, Docker, Docker compose._

sudo apt-get update && sudo apt-get upgrade;
sudo apt-get install git vim python3-pip docker docker-compose nginx

^^ above command is sufficient to get instance ready 8K.

**Comment by JamesKunstle** [comment]
_Author 8K architecture overview slides (part 4 of workshop)._

Created first draft on Miro

https://miro.com/app/board/uXjVPiBEz6k=/?share_link_id=756901575414

Access restricted to everyone, please ask for access explicitly if interested.

**Comment by JamesKunstle** [comment]
_Update 8K docs, README, License, and Login (not for SCaLE but for good measure)_

Added MIT license to repo, opened pull request for Login documentation, opened PR to update README to point to Login documentation in docs/AUGUR_LOGIN.md

**Comment by cdolfi** [comment]
@JamesKunstle everything is looking awesome, good call on adding MIT license. Will check out the miro board once I get access

**Comment by JamesKunstle** [comment]
_Validate concurrent Aug+8K deployment on bare metal (Redis collision?)._

Can easily remap redis and 8knot ports in the docker-compose.yml file so there shouldn't be a collision problem with concurrent use.

**Comment by JamesKunstle** [comment]
(3/9/23) Overview

Part 1:
- [ ] Sean's workshop style for Augur- does he need slides to go over architecture / collection?
- [ ] Need some background slides on Augur's motivation from Sean to introduce walkthrough- context.
- [ ] How to hand out credentials for Ubuntu20.0x boxes for follow-along attendees. Templated box replication.

Part 2:
- [ ] Architecture overview slide that points to Miro.
- [ ] Hard-architecture (pod-wise) intro slide, compose overview.
- [ ] Deployment instruction slide.
- [ ] Augur integration overview slide.
- [ ] Verify 8K on Ubuntu 20.0x, same boxes at Augur, so we don't need separate instances.
- [ ] Same credentials question- how to give everyone access to their own instances.
- [ ] Add VSCode SSH extension instructions to some doc.

Part 3:
?

Part 4:
- [ ] Jupyter hub launched in EC2 instance for multiple users? Other solution?
- [ ] Get PR merged for workshop visualization.

**Comment by JamesKunstle** [comment]
https://docs.google.com/presentation/d/1G2jN7o1-DVxPeZlPk51jcuh7YTQ8sbTnwm867koj53k/edit?usp=sharing
