### ISSUE TITLE
New Visualization: Activity by weekday and hour of day

### ISSUE THREAD

**Issue by cdolfi** [oss-aspen/8Knot#284]
This visualization will be used in the SCaLE workshop and further integrated into the application 

DATA: 
The first round pass will use timestamps of Issues and PRs open and close time. Potential for adding more activity 
UPDATE: Commits are the only github data point that holds timezone data. With the author and committer time stamps it gives a decent view into contribution activity 

VISUALIZATION: 
There will be a toggle view between seeing the data by day of week and by hour of day. Both will be histograms 

TODOS: 

- [x] Import data 
- [x] preprocess timestamps for weekday 
- [x] preprocess timestamps for hourly (figure out impacts of timezones )
- [x] create day of the week histogram 
- [x] create hour of day histogram 
- [ ] determine concise title
- [x] Fill in graph info

**Comment by cdolfi** [comment]
@JamesKunstle lmk if you have any title ideas for this viz

**Comment by JamesKunstle** [comment]
@cdolfi I think this is done, can we close this issue?

**Comment by cdolfi** [comment]
@JamesKunstle yes good call
