### ISSUE TITLE
Project Kepler (

### ISSUE THREAD

**Issue by kimberlycraven** [oss-aspen/8Knot#293]
https://github.com/sustainable-computing-io/kepler
https://github.com/sustainable-computing-io/kepler-model-server'
https://github.com/sustainable-computing-io/kepler-operator
https://github.com/sustainable-computing-io/kepler-estimator
https://github.com/sustainable-computing-io/kepler-action

**Comment by kimberlycraven** [comment]
Also https://github.com/Kepler-Project

**Comment by cdolfi** [comment]
All repos are now being collected on, should be fully populated in the next 1-3 days
