### ISSUE TITLE
Admin user group integration from Augur front end.

### ISSUE THREAD

**Issue by JamesKunstle** [oss-aspen/8Knot#309]
The folks at https://github.com/chaoss/augur have added Admin-level user groups.

This is implemented by having the user groups of the **Augur account that links a deployment of 8Knot** be visible to all other users of the same 8Knot instance. 

i.e. the user who registers a given 8Knot appication- who receives the client secret and application id- will take on the Admin group role.

There are new API end-points described in this issue:
https://github.com/chaoss/augur/issues/2276

We need to incorporate the use of these new endpoints so that when any user logs into 8Knot they receive both their own user groups and the admin-level groups.

May need to de-dupe groups for Admin users who also log into 8Knot.

**Comment by JamesKunstle** [comment]
- [ ] Check API endpoints w/ Postman 
- [ ] Implement new Admin user API endpoint in login logic of 8Knot
- [ ] De-dupe if necessary for Admin user on 8Knot

**Comment by cdolfi** [comment]
@JamesKunstle is this closed by #311?
