### ISSUE TITLE
refactor login logic

### ISSUE THREAD

**Issue by JamesKunstle** [oss-aspen/8Knot#310]
index/index_callbacks.py::augur_user_login is a mess.

going to refactor as a part of #309 

both should be done by EOD (4/25)

**Comment by JamesKunstle** [comment]
will be splitting flow into:
(1) is login explicit? -> authorization code in URL
(2) is login implicit? -> startup 'refresh_groups' flag set

otherwise skip login logic altogether; just changing pages: return immediately.

**Comment by cdolfi** [comment]
@JamesKunstle does #311 close this?
