### ISSUE TITLE
Get rid of error messages with 8knot_debug

### ISSUE THREAD

**Issue by sgoggins** [oss-aspen/8Knot#316]
**Describe the bug**
Set 8knot_debug=False in the env.list file, but it still shows errors (configured behind https): 
![image](https://user-images.githubusercontent.com/379847/236251025-b6aceab9-93b2-4c29-87db-1465f1437923.png)

**To Reproduce**
1. Install 8Knot
2. Configure nginx
3. Configure https
4. Watch the errors still show up

**Expected behavior**
DEBUG Mode off == No error display

**Comment by JamesKunstle** [comment]
This was patched by fixing the '8KNOT_DEBUG=True' flag checking
