### ISSUE TITLE
investigate more sustainable login paradigm

### ISSUE THREAD

**Issue by JamesKunstle** [oss-aspen/8Knot#338]
Login is pretty ugly as it's currently designed.

Handoff of parameters should be done on the front-end only (not server-side). 

This requires:

- [ ] Parsing URL changes on the client-side to check whether we're attempting a login.
- [ ] Attempting to authorize client usage of server user details from client.
- [ ] Consuming user information (groups) and populating the fields of related React components WITHOUT triggering a page refresh.

In an ideal world, login will leave the graphs that are present alone, not triggering a re-render but still updating the appropriate fields that are appropriate (username field, button text, search bar options, highlighted user groups). On-the-fly interaction with the Dash/React components as they are in the interface?

**Comment by JamesKunstle** [comment]
>> probably requires learning React and Flask

**Comment by sgoggins** [comment]
I wonder if this warrants a design huddle with @Ulincsys and I coming to Beantown. John doesn't like sportsball, so I insist we take him to a Red Sox game and teach him the real Boston.

**Comment by sgoggins** [comment]
I agree with this point. It works, and not too badly, there are just some clunky parts now that we've done it that I think would benefit from some whiteboard time. @Ulincsys has a pretty sophisticated understanding of the issues, as do you @JamesKunstle ... together I think we could figure out a more optimal path leveraging what we learned from our first effort.

**Comment by sgoggins** [comment]
I think with the group of us all in a room and the right number of days, we could probably actually get it done.

**Comment by Ulincsys** [comment]
I'm available whenever
