### ISSUE TITLE
New page: Welcome

### ISSUE THREAD

**Issue by JamesKunstle** [oss-aspen/8Knot#353]
Let's replace the 'Home' page and its metrics with a 'Welcome' page that describes how to use the app.

The 'Welcome' page will have the following content:

- [x] Brief mission statement about 8Knot
- [x] Plotly visualization tool intro
- [x] Reference to the 'Info' page 
- [ ] Walkthrough of how to use the Augur Front-end feature
- [x] General description of pages

**Comment by JamesKunstle** [comment]
working on this- new page is super ugly, need some guidance from people who know how to design websites.

**Comment by JamesKunstle** [comment]
@cdolfi 
Will be submitted for review at latest by mid-day (6/6), hopefully done (6/5)

**Comment by JamesKunstle** [comment]
https://www.youtube.com/watch?v=iTbyMPgV2aw

**Comment by JamesKunstle** [comment]
@cdolfi 
We can continue this one. I'm going to work on new sections for these instructions on the Welcome page:

- [ ] Logging in as a new user.
- [ ] How to create a new user group, see that group available in 8Knot.
- [ ] Requesting collection of new repos.
- [ ] See catalog of repos already available.

**Comment by JamesKunstle** [comment]
Currently planning out the sub-structure of the page. I think that each of the instructions sections should fold up with only one displayed by default. The user will tab through the available options so that the page isn't cluttered with all of the instructions at once.

**Comment by cdolfi** [comment]
Update from the last PR: final portion of this work to be done: " add instructions for creating user groups from the catalog, and for requesting collection using their user groups"

**Comment by JamesKunstle** [comment]
3/5 done- as Cali pointed out, final steps are:

- [ ] instructions for creating user groups
- [ ] instructions for requesting repo collection
