### ISSUE TITLE
Edit date range under "Company" Tab

### ISSUE THREAD

**Issue by lenicatko** [oss-aspen/8Knot#362]
**Describe the bug**
When the user chooses the data range from when they want to show the data from, it is showing the starting date January 2005. It is a bit confusing how to change the date or what format of the data you should use (the format shows up only when you click on some date). 

**To Reproduce**
1. Go to 'Company Tab'
2. Click on 'Start Date' or 'End Date" of any of the charts

**Expected behavior**

- When somebody wants to choose the date range, it is undestandable, what a date format person should use, for example "dd/mm/yyyy"
- The data range starts with the current month and year instead of January 2005

**Screenshots**

![image](https://github.com/oss-aspen/8Knot/assets/62905777/99b3e30b-276e-40bf-9528-3a665b17fdab)

**Comment by JamesKunstle** [comment]
@lenicatko Thanks for the bug report! We'll add this to our roadmap.

**Comment by lenicatko** [comment]
Thank you @JamesKunstle for the update! And let me know if you need to test it or anything!
