### ISSUE TITLE
Please add these orgs

### ISSUE THREAD

**Issue by jansche** [oss-aspen/8Knot#365]
**List the direct Git links to be added to our Augur database**
https://github.com/microcks
https://github.com/postmanlabs
https://github.com/postman-open-technologies

Thanks!

**Comment by JamesKunstle** [comment]
@jansche Just added those github orgs- collection will proceed in the background and should be available soon!

**Comment by jansche** [comment]
Thank you, @JamesKunstle !

**Comment by jansche** [comment]
Hi @JamesKunstle - I prematurely closed the issue, now I'm wondering how long it may take until the data is available. My apologies.

**Comment by cdolfi** [comment]
closing as data has been collected
