### ISSUE TITLE
Enhancement: Deploy compose with load balancer ahead of web server

### ISSUE THREAD

**Issue by JamesKunstle** [oss-aspen/8Knot#393]
Currently, we can't boot more than one web server container to scale performance because that container binds to the :8050 address.

Instead, a load balancer should sit between the web server and the target socket so that we can dynamically bind other web servers to the load balancer in the future, and the LB stays bound to the desired port.

**Comment by JamesKunstle** [comment]
Made this work in a toy application.
Small document describing method: https://medium.com/@vinodkrane/microservices-scaling-and-load-balancing-using-docker-compose-78bf8dc04da9

**Comment by cdolfi** [comment]
closed by #408
