### ISSUE TITLE
Create testing framework

### ISSUE THREAD

**Issue by JamesKunstle** [oss-aspen/8Knot#4]
Our application lacks any testing process before it is deployed or merged into dev or main. A difficulty in testing our app is that the data we are using are constantly updating- we need to target functions of the app that are data-agnostic.

The following are good candidate technical tests:
- [ ] Augur database is available
- [ ] Query to Augur with known return (up to max historical time) matches previously expected return value (past data isn't changing underfoot)
- [ ] Augur query of reasonably large size doesn't take too long
- [ ] App doesn't raise any runtime errors on deployment (run the app, hooks into logging for graph rendering)
- [ ] Large query takes any amount of time but doesn't error out.
- [ ] Moving between tabs w/ web driver changes url route as expected (Selenium)

We should have the long-run ability to test:
- [ ] different versions of python
- [ ] different operating systems (good practice for contributor accessibility)

We'll begin by implementing tests in PyTest and move to using Tox later when we want to test across environments. GithubActions handles these OS environments as well, so that's an option.

**Comment by cdolfi** [comment]
@JamesKunstle should this still be open?

**Comment by JamesKunstle** [comment]
@cdolfi Definitely, working on choosing our stack for this (pytests, Tox, Selenium, etc.)

**Comment by JamesKunstle** [comment]
We need the container of our built image to be running (this will be our ultimate production environment) and to attach to this running container and run a suite of python tests. 
i.e.

1. Running on ubuntu-latest
2. Checkout branch in Github Actions runner
3. build Docker image, run image as container (app.py will run because this is the CMD of the docker container)
4. Run tests (app will be running because by exiting the app we kill the docker container but this shouldn't be a problem).
5. Report failures to standard out, succeed if no errors. 

This is a tricky workflow because we need to run the tests from outside of the docker container ON the code that is in the container environment (verifying that the code that is in that environment is going to succeed.)

Redirection of standard out for pytest failures could also be a problem but whether it is or not is currently unknown.

**Comment by JamesKunstle** [comment]
Solution appears to be using the "docker exec ---" command with the -it flags to redirect the standard output of the running container to that of the host container. Will investigate and note.

**Comment by JamesKunstle** [comment]
There are lots of references to this problem having an incomplete solution. 

(how to use image just built to run tests)
https://stackoverflow.com/questions/71494742/github-workflows-how-do-i-reference-the-image-i-have-just-built-and-pushed-in-t

(using docker with github actions)
https://stackoverflow.com/questions/57549439/how-do-i-use-docker-with-github-actions

(running a built docker image inside of the running ubuntu image)
https://aschmelyun.com/blog/using-docker-run-inside-of-github-actions/

It seems like a pretty standard way to handle this workflow, as documented through correspondence on forums, is to push the built container to a registry and then pull that same image down to be used as the base image of the next workflow job. This seems really kludgey to me, but the documentation says that the difference Jobs of the Github Action use different processes entirely and don't share a namespace. This means that the state of the machine between jobs isn't identical, at least functionally.

**Comment by JamesKunstle** [comment]
Current process:

- [ ] Job 1 checks out the branch and builds the image, pushing it to quay
- [ ] Job 2 uses that image, running it as a container and using the 'run' argument to tell it to run tests.

**Comment by JamesKunstle** [comment]
In the interest of moving along, we'll try one more option which is to use a built container to checkout our code and to run tests there, promoting the container if the tests pass. If that doesn't appear to work correctly, we'll move on from the CI component and deliver CD.

**Comment by cdolfi** [comment]
@JamesKunstle can this be closed?

**Comment by JamesKunstle** [comment]
archived
