### ISSUE TITLE
Update OAuth2.0 flow for Augur frontend

### ISSUE THREAD

**Issue by JamesKunstle** [oss-aspen/8Knot#401]
Add `/login` and `/register` routes to Flask application server and use Flask-Login with Flask-Session to securely handle user sessions.

**Comment by JamesKunstle** [comment]
Have worked on this substantially in the past sprint- will be building a toy example for my [demonstration repo](https://github.com/JamesKunstle/easy-flask-boilerplate) while will then be applied to 8Knot.

**Comment by JamesKunstle** [comment]
Implemented Miguel Grinberg's OAuth2.0 flow in a demo application:
https://github.com/JamesKunstle/easy-flask-boilerplate/tree/add-oauth

Will be repeating this for 8Knot. Lots of lessons learned from this process.

**Comment by JamesKunstle** [comment]
Deciding, for the time being, to not restrict session communication via Secure cookie setting.

In the future, we'll likely need to handle non-ephemeral user state (session will key into redis key/value pair that'll reference the real username of the user) but for now the data is so quick to download that we don't have to worry about that.

**Comment by JamesKunstle** [comment]
Authentication via OAuth works now, and I feel good about security. Now, I need to design the way that the application handles the users data.

The data in question is the user's group set. These group sets can be very large, such as one case where a group had 20k repos in it. 

Right now, the groups are queried via a long callback (assuming the user is logged in) and stored in the local storage of the browser. With user authentication and sessions, we could switch to using server-side group caching. We could also design deferred collection, so sufficiently large groups aren't collected until requested by the user.

To decide how this works, I need to learn how to implement an asynchronous API in Flask so that a client-side callback in a Dash app can request user groups, which will be collected ad-hoc and stored in-browser for the time being.

**Comment by JamesKunstle** [comment]
Celery has good documentation on how an asynchronous workflow should be implemented. These routes should require login.
https://flask.palletsprojects.com/en/2.3.x/patterns/celery/

**Comment by JamesKunstle** [comment]
Followup: The redis creator discourages the use of multiple DBs in the same instance. It's so lightweight to spin up another Redis instance w/ Compose and Openshift that that's probably the right thing to do, full stop.

**Comment by JamesKunstle** [comment]
Discovered that #428 is required to finish this reimplementation. Finishing this issue will be the midway point in updating how user groups are handled.

**Comment by cdolfi** [comment]
closed with #477
