### ISSUE TITLE
Enhancement: Inform user of Plotly view change ability

### ISSUE THREAD

**Issue by cdolfi** [oss-aspen/8Knot#43]
Plotly gives the ability to change view, which would be important to users with tables that have edited views and a user wants to see a different subset. Determine how to have noted functionality pop up. This may already be a plotly functionality that may need to be turned on

**Comment by akshayamaujey** [comment]
To enable this functionality, you can use the subplot() method in Plotly.
import plotly.express as px
import pandas as pd

# Load data
df = pd.read_csv("data.csv")

# Create a scatter plot
fig = px.scatter(df, x="column1", y="column2", color="column3")

# Add subplots
fig.update_layout(
    xaxis=dict(title="Column 1"),
    yaxis=dict(title="Column 2"),
    updatemenus=[dict(type="buttons",    showactive=False,   buttons=[dict(label="View 1", method="update", args=[{"visible": [True, False, False]}, {"title": "View 1"}]), dict(label="View 2", method="update", args=[{"visible": [False, True, False]}, {"title": "View 2"}]), dict(label="View 3", method="update", args=[{"visible": [False, False, True]}, {"title": "View 3"}])])]
)

# Show plot
fig.show()
( Can you assign this query ?)
