### ISSUE TITLE
"Contributor Prolificacy in x Month Windows" title change

### ISSUE THREAD

**Issue by cdolfi** [oss-aspen/8Knot#471]
Ive gotten feedback from multiple people that they do not know what "prolificacy" means (and even though ive looked it up before each time I have to re google because I dont remember it either). Lets come up with a different title with a more commonly known word

**Comment by cdolfi** [comment]
@christinaexyou hm I dont know about traffic. This visualization gives a view into the minimum number of contributors that compose a certain percentage of a specific contribution type. Noodling on this as well today

**Comment by christinaexyou** [comment]
@cdolfi "Conditional Contributor Engagement/Participation..." ?, conditioned on the different adjustable parameters in the visualization.

**Comment by JamesKunstle** [comment]
What about something like "Contributor Volume of Contribution: ${action_type}" where action_type is replaced by "Commits", "PRs", etc.

**Comment by cdolfi** [comment]
@JamesKunstle I really like your suggestion. For some reason it feels like there some be a term for "minimum number of x to meet a threshold" but after sitting on it for a week im not sure if there is.

**Comment by JamesKunstle** [comment]
@cdolfi I totally feel what you mean. Even noodling on it for a week, nothing short-hand comes to mind. I feel like that's why we have to lean on the term for the definition and just define "lottery factor" in the 'about' pane.

**Comment by cdolfi** [comment]
@JamesKunstle Agreed, and I am a big fan of using a term that is already adopted in other community analysis

**Comment by JamesKunstle** [comment]
Also: consider changing pie chart title too

**Comment by cdolfi** [comment]
@JamesKunstle I agree on the title change for the Pie chart as well. Maybe something like "(Activity type here) Lottery Factor" ?

**Comment by christinaexyou** [comment]
@cdolfi @JamesKunstle how does "Lottery Factor: Top {k} Contributors by {action type}" sound ?

**Comment by JamesKunstle** [comment]
@cdolfi @christinaexyou Yeah that sounds great to me. I think putting those things in the title is super useful.

**Comment by cdolfi** [comment]
closed as titles have been changed
