### ISSUE TITLE
8knot Page breakdown feedback

### ISSUE THREAD

**Issue by cdolfi** [oss-aspen/8Knot#473]
Once the page breakdown is on main, general feedback is needed on: 

- Titles of each of the page tabs 
- page descriptions on welcome page 
- page descriptions on pages themselves
- if If Contributor Pull Request Review Assignment and Issue should also be in the contributor by contribution page

**Comment by JamesKunstle** [comment]
Feedback note: 

I find that 'Contributions' and 'Contributors' look like the same word on my 14" screen. I have to squint to see the difference, even knowing that they're different independently. Replacing the word 'Contributions' with something else, or 'Contributors' with 'People' might be reasonable. Idk more thought needed.

<img width="1512" alt="Screenshot 2023-09-27 at 12 23 58 PM" src="https://github.com/oss-aspen/8Knot/assets/52969093/e82ec082-a532-4796-8eb0-591966c525d9">

**Comment by cdolfi** [comment]
@JamesKunstle ooo I like the people idea a lot. Thanks for the picture also, really helped me understand the issue
