### ISSUE TITLE
Add Kuadrant repositories 

### ISSUE THREAD

**Issue by lenicatko** [oss-aspen/8Knot#503]
**List the direct Git links to be added to our Augur database**
https://github.com/kuadrant
https://github.com/Kuadrant/limitador
https://github.com/Kuadrant/authorino
https://github.com/Kuadrant/architecture
https://github.com/Kuadrant/kuadrant-operator
https://github.com/Kuadrant/wasm-shim
https://github.com/Kuadrant/multicluster-gateway-controller

**Comment by cdolfi** [comment]
closed as collection is complete
