### ISSUE TITLE
Docker Container Build is Failing

### ISSUE THREAD

**Issue by sgoggins** [oss-aspen/8Knot#517]
**Describe the bug**
Docker container is failing on GitHub and in practice.

**To Reproduce**
1. Run Docker Container on a new machine and see it fail
2. Or, look at Docker test in README.md

**Expected behavior**
Winning.

**Comment by JamesKunstle** [comment]
Hey @sgoggins could you give some more details? I don't have that problem locally, I'm not totally sure what you're seeing.
