### ISSUE TITLE
Issues_Assignments and PR_Assignments too big for the browser memory

### ISSUE THREAD

**Issue by JamesKunstle** [oss-aspen/8Knot#548]
When rendering those visualizations, my browser tab spiked to ~1GB of memory used for the kubernetes org. 
Took 884 seconds to render PR assignments.

Suggestion: 
1. only look at top ~10 contributors by assignment, the rest are 'other'.
2. grab 'windows' of data at once, not all of the data.

**Comment by cdolfi** [comment]
closing as #548 is covering the same thing
