### ISSUE TITLE
Welcome page update: Reordering of tabs 

### ISSUE THREAD

**Issue by cdolfi** [oss-aspen/8Knot#569]
Recommendation from @geekygirldawn

- How 8Knot Works - this provides important context about 8Knot and the relationship with Augur
- Plotly Figure Tools (maybe rename to ‘Using 8Knot Visualizations’)
- 8Knot Pages - this is more obvious, so I’d put it below the visualization instructions
- Your Augur Account (maybe rename to ‘Logging into Augur’)
- Adding a User Group (maybe rename to ‘Creating Project Groups’)
- Note: User group is super confusing because it sounds like you are grouping users, rather than creating a group of orgs / repos under your user account.

**Comment by geekygirldawn** [comment]
I also recommend not having these as tabs, but as one giant page. I know that the extra scrolling isn't ideal, but I think that this is super important information that a lot of users won't notice if it's behind tabs in the middle of the page.
