### ISSUE TITLE
Contributor Prolificacy title discussion

### ISSUE THREAD

**Issue by cdolfi** [oss-aspen/8Knot#575]
Space to discuss other options for titles (again :) )

**Comment by geekygirldawn** [comment]
I also added this to the agenda for the next CHAOSS Data Science WG meeting (Jan 17), so we can discuss it there if you don't come up with something else before: https://docs.google.com/document/d/1jkAfGt97OGRwcdEn8hh5YyHQwoXRnOW96ikc_Aluo6M/edit
