### ISSUE TITLE
Project Velocity visualization not showing all of the repos selected

### ISSUE THREAD

**Issue by JamesKunstle** [oss-aspen/8Knot#629]
When I search the Quay org, only about 50% of the repos appear on the plot.

**Comment by JamesKunstle** [comment]
when rendering quay/quayctl and containers/podman it's obviously the case that the graph knows about both datapoints, but podman isn't being rendered.

**Comment by cdolfi** [comment]
Not sure if I am fully following what is happening here, can you describe the problem further? One thing to note is that it seems like there has been more repos added to the org after our initial collection so they were not in augur. I triggered collection on them now so they should be in, confirming with @sgoggins that thatll mean they get added to the quay repo group as well

**Comment by cdolfi** [comment]
Update: There are a few things happening here

- some projects arent collected on (triggered collection and talking with @sgoggins on collection delays) 
- some projects had 1 or more issue or pr actions as nan which was making the whole weighted set nan (pr in for that fix) 
- some did not have any issue or pr actions so they will not be plotted
