### ISSUE TITLE
Broken link to overview page

### ISSUE THREAD

**Issue by suehle** [oss-aspen/8Knot#636]
https://chaoss.community/software/ says "see Augur in action using [8-knot](https://metrix.chaoss.io/overview)."

That link (metrix.chaoss.io/overview) 404s.

**Comment by cdolfi** [comment]
@sgoggins Is there a place in chaoss that this issue should be put? Not sure which repo/area this falls under 

@suehle thank you for pointing this out!

**Comment by sgoggins** [comment]
@suehle : I pushed a correcting change to GitHub and it should be propogated to the website shortly.
