### ISSUE TITLE
Time to First Response - potential issue with the data in this visualization

### ISSUE THREAD

**Issue by geekygirldawn** [oss-aspen/8Knot#646]
Hello! I'm looking at the time to first response graph from https://metrix.chaoss.io/contributions, and the data doesn't look right to me for a project that I'm pretty familiar with:

<img width="688" alt="image" src="https://github.com/oss-aspen/8Knot/assets/1304299/3b8b8c09-945f-450d-8b14-7c136ba216d6">

Using the same database, this is what I get from my starter project health metrics script:
<img width="1472" alt="image" src="https://github.com/oss-aspen/8Knot/assets/1304299/d2701111-4ed4-461d-b0dc-b2db275c3af0">

The query generating this chart can be found at https://github.com/geekygirldawn/starter-health-model/blob/main/metrics/first_response.py 

I would expect for the gaps in the lines between these 2 visualizations to look very similar. It's definitely possible that there is something wrong with my query, but I wonder if maybe we are measuring the "response" differently. I'm assuming that you count reviews, comments, close, and merge all as a response? Any thoughts on why we're getting different results?

cc: @sgoggins

**Comment by cdolfi** [comment]
vmware-tanzu/velero

**Comment by geekygirldawn** [comment]
Note that this is the repo in the graphs I posted, but I'm seeing the same issue across all repos :)

**Comment by cdolfi** [comment]
@geekygirldawn Going to start looking into this more, but my suspicion is that the different is that our graph is plotting values on a daily interval vs totals over the span of a month. This would also make sense as they are both the same general shape
