### ISSUE TITLE
Repositories added to Augur do not appear in 8Knot

### ISSUE THREAD

**Issue by jwflory** [oss-aspen/8Knot#649]
**Describe the bug**

Following the CHAOSScon EU 2024 workshop, I added the [github.com/fedora-infra/](https://github.com/fedora-infra/) organization to Augur, but after several days, the repositories do not appear n 8Knot and all reports appear as `TODO`.

**To Reproduce**

1. Go to https://metrix.chaoss.io/
2. Sign in.
3. Click "Manage Groups"
4. Paste https://github.com/fedora-infra/ into the "New Repo or Organization URL" text box
5. Enter a custom group name with whitespace characters
6. Visit group after seven days pass, e.g. https://ai.chaoss.io/user/group/Fedora%20Infrastructure%20on%20GitHub
7. Reports column shows "TODO"
8. Go back to https://metrix.chaoss.io/
9. Searching "fedora-infra" returns no results in the search bar

**Expected behavior**

* Step 7 above should show something other than `TODO`
* Step 9 above should show the "fedora-infra" GitHub repositories and/or namespace as an option

**Screenshots**

![Screenshot of an Augur group once added from the dialogue for adding a new group](https://github.com/oss-aspen/8Knot/assets/4721034/f880c2dd-ea09-45e3-9521-1bda778087af)

**Additional context**

I followed the steps outlined during the CHAOSScon EU 2024 workshop.

**Comment by cdolfi** [comment]
tagging @sgoggins for visibility. https://metrix.chaoss.io/ is the CHAOSS (sean) managed instance of 8Knot, https://eightknot.osci.io/ is the "Red Hat" (me and james) managed instance. In the https://eightknot.osci.io/ instance fedora-infra is available!

**Comment by sgoggins** [comment]
@jwflory : I learned about how to ensure this occurs. There's a step I didn't know about and we have the repos there now, and I am issuing a devops patch to ensure they are there overnight in the future.
