### ISSUE TITLE
Oversaturated logs 

### ISSUE THREAD

**Issue by cdolfi** [oss-aspen/8Knot#653]
Is there any option to make it where the logs dont update every second when it is waiting on data so the logs are over saturated? This causes logs with information in them to not be visible 

<img width="982" alt="Screenshot 2024-03-10 at 10 07 16 AM" src="https://github.com/oss-aspen/8Knot/assets/47504866/6e0c0b92-2f78-4b66-8f42-787d694b9e16">

**Comment by JamesKunstle** [comment]
This is important because the _number_ of logs that are generated is informative. If you can't find something you're looking for, crtl-f for the thing you want, or run the app in the terminal rather than the vscode integrated terminal so you can see the entire historic output.
