### ISSUE TITLE
Weird search bar behavior results

### ISSUE THREAD

**Issue by cdolfi** [oss-aspen/8Knot#666]
<img width="1027" alt="Screenshot 2024-03-12 at 12 40 42 PM" src="https://github.com/oss-aspen/8Knot/assets/47504866/8fa1a78d-89a3-469c-8c5c-d3961519127c">

**Comment by cdolfi** [comment]
![Image](https://github.com/oss-aspen/8Knot/assets/47504866/54a14d78-1947-4f99-b26f-0961ebd3c2f2)

**Comment by JamesKunstle** [comment]
duplicate
