### ISSUE TITLE
BUG: hashicorp/terraform not showing up in search bar

### ISSUE THREAD

**Issue by cdolfi** [oss-aspen/8Knot#684]
I put [hashicorp/terraform](https://github.com/hashicorp/terraform) in to be collected on tuesday and it shows to be full collected in augur but not showing up in 8Knot

**Comment by cdolfi** [comment]
Looking at it any of the repos I put in on tuesday are not showing up

**Comment by JamesKunstle** [comment]
Fixed by restarting the application on Openshift
