### ISSUE TITLE
Integrate non-visualization "metrics" to Overview Page

### ISSUE THREAD

**Issue by cdolfi** [oss-aspen/8Knot#7]
Refer to the [miro board design](https://miro.com/app/board/uXjVORjEx30=/?invite_link_id=312825995436) for reference

The work pipeline for non visualization data points is TBA

Non-Visualizations Required for Completion(short hand, refer to miro board for more details):

- [ ] README Description if available
- [ ] mailing list (if accessible from repo)
- [ ] Code of Conduct (Y/N)
- [ ] License
- [ ] Contributor Guideline (Y/N)
- [ ] Website Link
- [ ] Social Media Link
- [ ] Languages in Repo
- [ ] Company Involvement List
- [ ] # of Releases 
- [ ] Last Release, number and date

**Comment by JamesKunstle** [comment]
In addition to the above metrics, the following should also be considered. these aren't meant to be full visualizations. they should be singular statistical or aggregate perspectives on the data.

- [ ] total # of commits
- [ ] current # of issues
- [ ] total # of issues
- [ ] current # of PRs
- [ ] total # of merged PRs
- [ ] total # of closed+unmerged PRs
- [ ] avg. # of lines per commit, # of insert and # of deleted
- [ ] avg. age of open PRs
- [ ] historical avg. age of merged PR
- [ ] avg. age of issues
- [ ] historical avg. age of closed issues
- [ ] # unaddressed PRs; no response from person other than author
- [ ] # unaddressed Issues; no response from person other than author
- [ ] avg. # of PR messages
- [ ] avg. # of issue messages
- [ ] top issue tags, ordered by count
- [ ] survival analysis of issue closure
- [ ] survival analysis of PR close+merge
- [ ] survival analysis of time-to-response on issues from non-authors
- [ ] survival analysis of time-to-response on PRs from non-authors

**Comment by cdolfi** [comment]
@JamesKunstle Lets talk more. I feel like a subset/all straight metrics and a few vizs would be a good solution for the home page

**Comment by JamesKunstle** [comment]
@cdolfi working on this with SQL queries in Rappel branch:

https://github.com/oss-aspen/Rappel/pull/180

**Comment by JamesKunstle** [comment]
#308 #348 affect this issue. I think that the Home page could be reworked to show the data that @cdolfi originally suggested for this- e.g. the presence of some documents by name, number of releases, time since last release, social media link, languages used, etc. Those ARE mostly time-agnostic and are interpretable in consideration of a project's entire lifespan.

**Comment by cdolfi** [comment]
@JamesKunstle What are your thoughts of integrating this in the new home page?

**Comment by JamesKunstle** [comment]
@cdolfi I agree with myself from 5/25:

> #308 #348 affect this issue. I think that the Home page could be reworked to show the data that @cdolfi originally suggested for this- e.g. the presence of some documents by name, number of releases, time since last release, social media link, languages used, etc. Those ARE mostly time-agnostic and are interpretable in consideration of a project's entire lifespan.

We can make the integration of these 'evergreen' metric things a future priority.
