### ISSUE TITLE
What is your policy on adding smaller orgs/repos to the dashboard?

### ISSUE THREAD

**Issue by CommanderStorm** [oss-aspen/8Knot#701]
**List the direct Git links to be added to our Augur database**

I don't know what your policy on adding smaller repository or orgs is, as this form exists but the [repo-list](https://eightknot.osci.io/repo_overview) only contains things from the CHAOSS org.

Do you think the org https://github.com/TUM-Dev or (not connected) https://github.com/louislam/uptime-kuma meet your size/elegility-requirement?

**Comment by JamesKunstle** [comment]
You're absolutely welcome to add any public repos your interested in! The `chaoss` value in the searchbar is just the default. Please follow the instructions on the `Welcome` page of 8Knot to create an Augur account and schedule the collection of the repos your interested in.
