### ISSUE TITLE
Repo General Info Missing Information

### ISSUE THREAD

**Issue by Pizza-Ria** [oss-aspen/8Knot#707]
**Describe the bug**
I ran the 8knot report for the repo github.com/grommet/grommet.  

**To Reproduce**
1. Click on Repo Overview
2. Scroll down to Repo General Info
3. Both Code of Conduct & Contributor Guidelines show "File Not Found"
4. Both files are actually in the repo but apparently not getting picked up.  See, https://github.com/grommet/grommet/blob/master/CODE_OF_CONDUCT.md and https://github.com/grommet/grommet/blob/master/CONTRIBUTING.md - both are listed from the main repo (see screenshot).  

**Expected behavior**
Expect to see both files detected.
**Screenshots**

**Additional context**
![Grommet Repo Screenshot](https://github.com/oss-aspen/8Knot/assets/46799628/d0177a8f-244f-4049-b016-2ce6f936d340)
![Grommet Repo General Info](https://github.com/oss-aspen/8Knot/assets/46799628/fc0c85b8-08c2-4df5-bc5e-298cb479fbfc)

**Comment by cdolfi** [comment]
![Image](https://github.com/oss-aspen/8Knot/assets/47504866/31e06c15-5b18-4a66-98e8-9a037868949d)

From what I can see here (and in your picture) it lists "File found" for Contributor Guidelines and CoC. Let me know if I am missing something!

**Comment by cdolfi** [comment]
@Pizza-Ria Hi, bumping to see if this can be closed or if there is another issue I am not seeing

**Comment by cdolfi** [comment]
closing as no comment
