### ISSUE TITLE
Unable to login or use https://eightknot.osci.io/ is this expected?

### ISSUE THREAD

**Issue by Frooodle** [oss-aspen/8Knot#715]
**Describe the bug**

**To Reproduce**
1. Go to https://eightknot.osci.io/
2. Click on 'Augur log in/sign up'
Sends to me https://eightknot.chaoss.tv/user/authorize?client_id=xxxxxxxxxxxxxxxxxxxxxxx&response_type=code/user/authorize?client_id=xxxxxxxxxxxxxxxxxxxxx&response_type=code with took too long to respond, tried edge and brave browser

is the demo site unusable?

**Comment by Frooodle** [comment]
looking at docs at https://github.com/chaoss/augur?tab=readme-ov-file
should new URL be
https://metrix.chaoss.io/

**Comment by Frooodle** [comment]
seems other url is back

**Comment by cdolfi** [comment]
@Frooodle Sorry for the late response! So there are two instances of 8knot publicly available that connect to two different augur instances (will have different repositories in them). https://metrix.chaoss.io/ is managed and hosted by CHAOSS and https://eightknot.osci.io/ is hosted and managed by Red Hat's OSPO. We are looking to make some changes in the future to make it easier to differentiate between the two. At that time one (or both) must have been down. Both are up and you can use either!
