### ISSUE TITLE
ScilifelabDataCentre Organization Load Request

### ISSUE THREAD

**Issue by libcce** [oss-aspen/8Knot#716]
**List the direct Git links to be added to our Augur database**
https://github.com/ScilifelabDataCentre

**Comment by cdolfi** [comment]
Repos are now being loaded in!

**Comment by libcce** [comment]
[ScilifelabDataCentre](https://github.com/ScilifelabDataCentre) doesn't appear on the list here https://metrix.chaoss.io/. I searched for ScilifelabDataCentre and couldn't find it. Unless I'm not looking in the right place?

**Comment by cdolfi** [comment]
Repo load requests for issues opened on this repository is for https://eightknot.osci.io/. The chaoss one is managed by CHAOSS/ @sgoggins. Repos can be added to that instance by following the instructions on the home screen or sending a message in the chaoss #augur-8knot slack channel

**Comment by sgoggins** [comment]
@libcce : When did you add the repositories? It's likely they were not loaded right away. I'm looking into it.

**Comment by sgoggins** [comment]
@libcce : I did not see ScilifelabDataCentre GitHub org added recently, so I added it to those public instances as well. You will see some data within 24 hours. Some of the more detailed data used in 8Knot, like pull request reviews, comments, etc. take longer (~3 days) to get populated.

**Comment by libcce** [comment]
Thanks @cdolfi @sgoggins!

**Comment by sgoggins** [comment]
@libcce : I checked just now and you have a good amount of data for those repositories in place. Some of the stuff like PR Reviews and similar may not be finished yet, but most of it looks finished. Keen to hear your insights and suggestions!

**Comment by libcce** [comment]
Thanks! Definitely, we can chat, in-person and soon!
